# Generated by Django 4.0.3 on 2022-03-18 19:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'genre',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('Regular', 'Regular'), ('Children', 'Children'), ('New_Release', 'New_Release')], max_length=50)),
                ('genre', models.CharField(choices=[('Drama', 'Drama'), ('Romance', 'Romance'), ('Action', 'Action'), ('Comedy', 'Comedy'), ('Horror', 'Horror')], max_length=100)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('movie_poster', models.URLField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('popularity', models.CharField(blank=True, choices=[('5', '5'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1')], help_text='Captured as Rating between 0 -5 ', max_length=100, null=True)),
            ],
            options={
                'db_table': 'movies',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movie_type', models.CharField(choices=[('Regular', 'Regular'), ('Children', 'Children'), ('New_Release', 'New_Release'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Action', 'Action'), ('Comedy', 'Comedy'), ('Horror', 'Horror')], max_length=50, unique=True)),
                ('price', models.FloatField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'pricing',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RentOutMovies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('return_date', models.DateField()),
                ('day', models.DateField(default=datetime.date.today)),
                ('price', models.FloatField(blank=True, null=True)),
                ('returned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.movies')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rent_out_movie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChildrensMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_age', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('movie', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='movies.movies')),
            ],
            options={
                'db_table': 'childrens_movie',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NewRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_released', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('movie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movies.movies')),
            ],
            options={
                'db_table': 'movies_new_release',
                'managed': True,
                'unique_together': {('movie', 'year_released')},
            },
        ),
    ]
