# Generated by Django 4.0.3 on 2022-03-16 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('type', models.CharField(choices=[('Regular', 'Regular'), ('Children', 'Children'), ('New_Release', 'New_Release')], default=1, editable=False, max_length=11)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Drama', 'Drama'), ('Romance', 'Romance'), ('Comedy', 'Comedy'), ('Horror', 'Horror'), ('Animation', 'Animation')], default=1, editable=False, max_length=9)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('popularity', models.IntegerField(blank=True, help_text='Captured as Percentage', null=True)),
            ],
            options={
                'db_table': 'movie',
                'managed': True,
                'unique_together': {('title', 'genre')},
            },
        ),
        migrations.CreateModel(
            name='NewRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_release', models.IntegerField(choices=[(1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], default=2022)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('movie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='movies.movie')),
            ],
            options={
                'db_table': 'new_release',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ChildrensMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_age', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('movie', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='movies.movie')),
            ],
            options={
                'db_table': 'childrens_movie',
                'managed': True,
            },
        ),
    ]
