# Generated by Django 4.0.3 on 2022-03-18 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='movies',
            table='movies',
        ),
    ]
