# Generated by Django 4.0.3 on 2022-03-19 08:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentoutmovies',
            name='day_rented',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
