# Generated by Django 4.0.3 on 2022-03-19 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rentoutmovies_day_rented'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rentoutmovies',
            old_name='day_rented',
            new_name='number_of_days_rented',
        ),
    ]
