# Generated by Django 4.0.3 on 2022-03-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movies_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_poster',
            field=models.URLField(blank=True, null=True),
        ),
    ]
